import { createSlice } from "@reduxjs/toolkit";

// Initial state for the news slice
const initialState = {
  articles: [],
  loading: false,
  error: null,
};

// Create the slice
const newsSlice = createSlice({
  name: "news",
  initialState,
  reducers: {
    setArticles: (state, action) => {
      state.articles = action.payload;
    },
    setLoading: (state, action) => {
      state.loading = action.payload;
    },
    setError: (state, action) => {
      state.error = action.payload;
    },
  },
});

// Export the actions generated by the slice
export const { setArticles, setLoading, setError } = newsSlice.actions;

// Export the reducer to be added to the store
export default newsSlice.reducer;
